export enum AnimationEase {
  CubicBezier = "cubic-bezier(0.4, 0, 0.2, 1)",
  EaseIn = "easeIn",
  EaseOut = "easeOut",
  EaseInOut = "easeInOut",
  BackIn = "backIn",
  BackOut = "backOut",
  BackInOut = "backInOut",
  CircIn = "circIn",
  CircOut = "circOut",
  CircInOut = "circInOut",
  Anticipate = "anticipate",
  Linear = "linear",
  Steps = "steps(5, end)",
}
